apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: credit-review-portal-xcvp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: credit-review-portal-xcvp
    app.kubernetes.io/part-of: credit-review-portal
  name: credit-review-portal-xcvp
  namespace: burrzinga-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: credit-review-portal-xcvp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: credit-review-portal-xcvp
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:858c0bb9af9a9216047c5c56a88d3f9bcc66d8eb75185e1d3d2a0b397d7dd285
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
