apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: credit-review-portal-xcvp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: credit-review-portal-xcvp
    app.kubernetes.io/part-of: credit-review-portal
  name: credit-review-portal-xcvp
  namespace: burrzinga-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: credit-review-portal-xcvp
    weight: null
status: {}
