apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: credit-review-portal-xcvp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: credit-review-portal-xcvp
    app.kubernetes.io/part-of: credit-review-portal
  name: credit-review-portal-xcvp
  namespace: burrzinga-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: credit-review-portal-xcvp
status:
  loadBalancer: {}
